##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  自定义配置  ###################
custom:
  swagger-open: false #是否开启swagger (true/false)
  kaptcha-open: true #是否开启登录时验证码 (true/false)
  session-open: true #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: true #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  
# 阿里云OSS文件配置
oss:
  accessKeyId: wtiUZd71Qvb0zIsQ
  accessKeySecret: aOywWxrs9kc33CrhABv4f10gDqEttY
  bucketName: elsdocman
  openBucketName: elspicman
  openAccessUrl: http://elspicman.oss-cn-shenzhen.aliyuncs.com
  accessUrl: http://elsdocman.oss-cn-shenzhen.aliyuncs.com
  maxConnections: 200
  connectionTimeout: 50000
  socketTimeout: 30000
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  maxErrorRetry: 3
  private_host: http://elsdocman.oss-cn-shenzhen.aliyuncs.com
  public_host: http://elspicman.oss-cn-shenzhen.aliyuncs.com
  dir: els-dir/
  fileCatalog: Vietnam
  expireTime: 30
  sts_region: cn-hangzhou
  sts_servion: 2015-04-01
  sts_accessKeyId: RHFudPdGKX6J6iXW
  sts_accessKeySecret: simlYfROXu4tB6TNWe8MRjrn3jVqFm
  sts_roleArn: acs:ram::1596567596119360:role/readandwrite
 
  
#Els配置
els:
  els_subaccount: 1001
  els_station: sale
  els_isadmin: Y
  els_route: http://sit.beta.51qqt.com/ELSServer_XMJL
  els_frozen_flag: N
  els_accountvaliditydate: 2099-12-31
  els_isdel: N
  els_admin_code: admin
  els_admin_name: 管理
  els_app_account: paas_base_accountManage
  els_app_role: paas_base_roleManager

###################  服务端配置  ###################
server:
  port: 8080
  context-path: /manage

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  #redis:
    #host: localhost
    #port: 6379
    #password:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  #devtools:
    #restart:
      #enabled: false #是否开启开发者工具（true/false）
      #additional-paths: src/main/java
      #exclude: static/**,WEB-INF/view/**

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/els/jewellery/manage/**/mapping/*.xml
  typeAliasesPackage: com.els.jewellery.manage.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    #cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
custom:
  #文件上传目录(不配置的话为java.io.tmpdir目录)
  #file-upload-path: /Users/ithost/it/dev/files/portal_manage

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jewellery_manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 6235666
    filters: log4j,wall,mergeStat

# 账号库数据源
account:
  datasource:
    url: jdbc:mysql://112.74.96.60:3306/els_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: els
    password: C0#0p!vnHkNkK6jc

logging:
  level.root: info
  level.com.els: debug
  path: logs/
  file: portal_manage.log

---

##########################################################
###################  测试环境的profile  ###################
##########################################################
custom:
  #文件上传目录(不配置的话为java.io.tmpdir目录)
  file-upload-path: /mnt/local/files/portal_manage

spring:
  profiles: cs
  datasource:
    url: jdbc:mysql://localhost:4306/jewellery_manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: els
    password: els@195qqt.com
    filters: log4j,wall,mergeStat

# 账号库数据源
account:
  datasource:
    url: jdbc:mysql://112.74.96.60:3306/els_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: els
    password: C0#0p!vnHkNkK6jc

logging:
  level.root: info
  path: /mnt/local/logs/portal_manage/
  file: portal_manage.log

---

##########################################################
###################  正式环境的profile  ###################
##########################################################
custom:
  #文件上传目录(不配置的话为java.io.tmpdir目录)
  file-upload-path: /mnt/local/files/portal_manage

spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://47.88.231.144:4306/PORTAL?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: els
    password: els@51qqt.com
    filters: log4j,wall,mergeStat

# 账号库数据源
account:
  datasource:
    url: jdbc:mysql://112.74.96.60:3306/els_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: els
    password: C0#0p!vnHkNkK6jc

logging:
  level.root: info
  path: /mnt/local/logs/jewellery_manage/
  file: portal_manage.log
